sudo: required
services:
        - docker

before_install:
        - docker build -t cyberpunk1250/docker-react -f Dockerfile.dev .

script:
        - docker run cyberpunk1250/docker-react npm run test -- --coverage
